# Dockerfile para o script carguru.py

# Imagem base para o Python 
FROM python:3

# Diretório da app para o container
WORKDIR /app

# Cópia do script para dentro do container
COPY carguru.py .

# Comando para rodar script
CMD [ "python", "carguru.py" ]