# Dockerfile para o script gerar_hash.py

# Imagem base para o Python 
FROM python:3

# Diretório da app para o container
WORKDIR /app

# Cópia do script para dentro do container
COPY gerar_hash.py .

# Comando para rodar script
CMD ["python", "gerar_hash.py"]